config/routes.rb
TaobaoQrcode::Application.routes.draw do

  resources :feedbacks

  resources :logos

  root 'shops#current'

  concern :public_qr_code_service do
    collection do
      get :public_qr_code_service
    end
  end
  resources :items,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :download_zip
    end
    member do
      get :download_qr
      put :img_upload
      put :picture_upload
      get :qr_code_img
    end
  end

  resources :shops,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :current
      get :current_download_qr
      get :current_qr_code_img
      put :current_qr_upload

      get :current_card
      put :generate_card

      get :current_card_download_qr
      get :current_card_qr_code_img
      put :current_card_qr_upload
    end
  end
  get 'dashboard/faq' => 'dashboard#faq',as: :faq
  get 'dashboard/history' => 'dashboard#index',as: :history
  get '/:id' => "shortener/shortened_urls#show"
  post 'short_url/generate' => "short_url#generate"

  

end

app/controllers/shops_controller.rb
#coding: utf-8
#店铺管理
class ShopsController < ApplicationController
  include QrCodeService
  include ShopsHelper
  after_filter :save_shop_picture_upload_log,only: :current_qr_upload
  after_filter :save_shop_card_picture_upload_log,only: :current_card_qr_upload
  #GET shops/current
  def current
    @shop = current_shop_get
    render action: :show
  end
  #GET shops/current_card
  def current_card
    @shop = current_shop_get
    #获取shop card 信息
    @shop_card = ShopCard.find_by_sid(@shop.sid)
    @shop_card ||= ShopCard.new(nick: @shop.nick,sid: @shop.sid,
                                title: @shop.nick,shop_url: shop_url(@shop.sid),
                                shop_desc: @shop.desc
                               )
  end
  #PUT shops/current_qr_upload
  #上传店铺网址二维码到淘宝图片空间
  def current_qr_upload
    @shop = current_shop_get
    @picture = qr_picture_upload(shop_url(@shop_sid),@shop.title,:jpeg,params)
  end
  #GET shops/current_download_qr
  #下载店铺的qr_code
  def current_download_qr
    @shop = current_shop_get
    qr_download(shop_url(@shop_sid),@shop.title,:jpeg,params)
  end
  #get shops/current_qr_code_img
  #根据传入的参数获取qr_img
  def current_qr_code_img
    @shop = current_shop_get
    qr_img(shop_url(@shop_sid),:jpeg,params)
  end

  ############店铺名片相关action#########################
  #PUT shops/generate_card
  #生成店铺名片二维码
  def generate_card
    @shop = current_shop_get
    @shop_card = ShopCard.find_or_create_by(nick: @shop.nick,sid: @shop.sid,title: @shop.title)
    @shop_card.update_attributes(shop_card_params)
  end

  #PUT shops/current_qr_upload
  #上传店铺网址二维码到淘宝图片空间
  def current_card_qr_upload
    @shop = current_shop_get
    @shop_card = ShopCard.find_by_sid(@shop.sid)
    @picture = qr_picture_upload(@shop_card.build_vcard.to_s,@shop.title,:jpeg,params)
  end
  #GET shops/current_download_qr
  #下载店铺的qr_code
  def current_card_download_qr
    @shop = current_shop_get
    @shop_card = ShopCard.find_by_sid(@shop.sid)
    qr_download(@shop_card.build_vcard.to_s,@shop.title,:jpeg,params)
  end
  #get shops/current_qr_code_img
  #根据传入的参数获取qr_img
  def current_card_qr_code_img
    @shop = current_shop_get
    @shop_card = ShopCard.find_by_sid(@shop.sid)
    qr_img(@shop_card.build_vcard.to_s,:jpeg,params)
  end



  private
  def shop_fields
    %w[sid cid title nick desc bulletin pic_path created modified].join(",")
  end
  def current_shop_get
    args = {
      method: 'taobao.shop.get',
      session: session_key,
      fields: shop_fields,
      nick:  taobao_nick
    }
    taobao_response = TaobaoSDK::Session.invoke(args)
    taobao_response.shop
  end
    # Never trust parameters from the scary internet, only allow the white list through.
  def shop_card_params
    params.require(:shop_card).permit!
  end
  #记录图片上传记录
  def save_shop_picture_upload_log
    ShopPictureUploadLog.create(sid: @shop.sid,nick: taobao_nick,
                                picture_path: @picture.picture_path,
                                picture_id: @picture.picture_id,
                                title: @picture.title)
  end
  def save_shop_card_picture_upload_log
    ShopCardPictureUploadLog.create(sid: @shop.sid,nick: taobao_nick,
                                picture_path: @picture.picture_path,
                                picture_id: @picture.picture_id,
                                title: @picture.title)
  end

end

app/helpers/shops_helper.rb
#coding: utf-8
module ShopsHelper
  #根据店铺sid获取店铺网址
  def shop_url(sid)
    "http://shop#{sid}.taobao.com"
  end
  #得到店标url
  def shop_logo_url(logo_path)
    "http://logo.taobao.com/shop-logo#{logo_path}"
  end
  #店铺网址共享json对象
  #qr_content 二维码
  def shop_share_json(shop)
    {
      pic:    short_url(public_qr_code_service_shops_url(content: shop_url(shop.sid))),
      text:   "#{shop.title}-诚信卖家,扫描二维码进店选购",
      url:    short_url(public_qr_code_service_shops_url(content: shop_url(shop.sid))),
      comment: shop.desc
    }.to_json
  end
  #店铺名片共享json对象
  def shop_card_share_json(shop_card)
    {
      pic:    short_url(public_qr_code_service_shops_url(content: shop_card.build_vcard.to_s)),
      text:   "#{shop_card.title}-诚信淘宝卖家,扫描二维码进店选购",
      url:    short_url(public_qr_code_service_shops_url(content: shop_card.build_vcard.to_s)),
      comment: shop_card.shop_desc
    }.to_json
  end
end

app/views/shops/_vcard.haml
= form_for shop_card,url: {action: :generate_card,format: :js},method: :put,remote: true,html: {class: "vcard-wrapper vcard-form","data-type" => "script"} do |f|
  %table.table.table-condensed
    %tr
      %td{colspan: 2}
        .input-prepend
          %span.add-on 店铺名称
          = f.text_field :title,class: :span6
    %tr
      %td
        .input-prepend
          %span.add-on 电话
          = f.text_field :phone,class: "span2"

      %td{rowspan: 4}
        = f.text_area :shop_desc,rows: 7,class: :span4
    %tr
      %td
        .input-prepend
          %span.add-on &nbsp;QQ
          = f.text_field :qq,class: "span2"
    %tr
      %td
        .input-prepend
          %span.add-on 旺旺 
          = f.text_field :wangwang,class: "span2"
    %tr
      %td
        .input-prepend
          %span.add-on 微信 
          = f.text_field :weixin,class: "span2"
    %tr
      %td{colspan: 2}
        .input-prepend
          %span.add-on 店铺网址
          = f.text_field :shop_url,class: "span6",readonly: true
    %tr
      %td{colspan: 2}
        .input-prepend
          %span.add-on 实店地址
          = f.text_field :address,class: "span6"

app/views/shops/_vcard_tip.haml
.hero-unit
  %h3 生成店铺名片
  %p
    该信息以标准的vcard格式存储,手机扫描时,店铺信息会自动添加到手机通讯录
  %p
    %a{href: 'http://zh.wikipedia.org/wiki/VCard',target: "_blank"} 了解vcard
  %p
    %a.btn.btn-primary.btn-large.btn-generate-shop-vcard  生成名片二维码

app/views/shops/current_card.haml
%ul.nav.nav-tabs
  %li
    = link_to "店铺网址",current_shops_path
  %li.active
    = link_to "店铺名片",current_card_shops_path

%h4 生成店铺名片二维码
.row
  .span12
    .well.well-small.clearfix
      .pull-left.vcard
        = render "vcard",shop_card: @shop_card
      .pull-right.span4
        = render "vcard_tip"

.row
  .span12
    .well
      .clearfix
        .well.well-small.pull-left
          .shop-card-qr
            -# 对于含有中文字符的二维码,需要强制转换为cp852
            = render "shared/qr",:content => @shop_card.build_vcard.to_s.force_encoding('cp852'),:qr_label => nil,:logo_url => shop_logo_url(@shop.pic_path)
        .qr-config.pull-left
          = render "shared/qr_config"

      .well.well-small.clearfix
        .pull-left.qr-operates-upload
          .btn-group
            %a.btn.btn-picture-upload-single{:href => current_qr_upload_shops_path(:format => :js),
            "data-origin-href" =>  current_card_qr_upload_shops_path(:format => :js),
            "data-method" => :put,
            "data-disable-with" => "正在上传...",
            "data-remote" => true,:rel => "nofollow",
            "data-toggle" => "tooltip",:title => "将二维码放入淘宝图片空间"}
              %i.icon-cloud-upload
              上传到淘宝图片空间

            %a.btn.btn-download-qr-single{:href => current_download_qr_shops_path,
            "data-origin-href" =>   current_card_download_qr_shops_path,
            "data-no-turbolink" => true,
            "data-toggle" => "tooltip",:title => "下载二维码图片到本地"}
              %i.icon-download-alt
              下载到本地

        .pull-right.qr-operates-share
          -# Baidu Button BEGIN 
          #bdshare.bdshare_t.bds_tools.get-codes-bdshare.shop-card-share{:data => "#{shop_card_share_json(@shop_card)}"}
            %a.bds_qzone  QQ空间
            %a.bds_tsina 新浪微博
            %a.bds_tqq 腾讯微博
            %a.bds_renren 人人网
            %span.bds_more 更多
          = render "shared/bdshare"
          -# Baidu Button END
      .well.well-small.qr-url
        .input-prepend.input-append{"data-toggle" => "tooltip","data-placement" => "bottom",:title => "拷贝图片网址到剪贴板"}
          %span.add-on
            %i.icon-link
          %span#qr_code_img_url.span8.uneditable-input{"data-origin-url" => public_qr_code_service_shops_url(content: @shop_card.build_vcard.to_s)} 
            = public_qr_code_service_shops_url(content: @shop_card.build_vcard.to_s)
          %a#btn_clip.btn.btn-clip{"data-clipboard-target" => 'qr_code_img_url',:type => :button}
            %i.icon-copy
        .alert.alert-success.clip-success{style: 'display : none;'}
          %button.close{type: "button","data-dismiss" => "alert"} &times;
          已将二维码网址复制到剪贴版


        .alert.alert-info
          您可复制该URL到需要显示的地方

%h4 评论
.row
  .span12
    .well
      -#Duoshuo Comment BEGIN
      .ds-thread{"data-title" => "店铺名片二维码","data-author-key" => taobao_nick,"data-url" => current_card_shops_url}
      -#Duoshuo Comment END

app/views/shops/current_card_qr_upload.js.erb
$.notifyBar({
    cssClass: 'success',
    html: '<%="店铺#{@shop_card.title}的二维码图片已添加上传到淘宝图片空间!" %>',
    delay: 5000,
    animationSpeed: "normal",
  });  
$('.jquery-notify-bar').addClass('alert').addClass('alert-success');

app/views/shops/current_qr_upload.js.erb
$.notifyBar({
    cssClass: 'success',
    html: '<%="#{@shop.title}的二维码图片已已上传到淘宝图片空间!" %>',
    delay: 5000,
    animationSpeed: "normal",
  });  

$('.jquery-notify-bar').addClass('alert').addClass('alert-success');

app/views/shops/generate_card.js.erb
var qr = '<%= escape_javascript(render "shared/qr",:content => @shop_card.build_vcard.to_s.force_encoding('cp852'),:qr_label => nil,:logo_url => shop_logo_url(@shop.pic_path)) %>';
$('.shop-card-qr').html(qr);
$('.shop-card-qr').unblock();
$('.shop-card-qr').trigger('refresh')

app/views/shops/show.haml
%ul.nav.nav-tabs
  %li.active
    = link_to "店铺网址",current_shops_path
  %li
    = link_to "店铺名片",current_card_shops_path

%h4 
  = @shop.title

.row
  .span12
    .well
      .clearfix
        .large-qr.pull-left
          = render "shared/qr",:content => shop_url(@shop.sid),:qr_label => nil,:logo_url => shop_logo_url(@shop.pic_path)
        .qr-config.pull-left
          = render "shared/qr_config"

      .well.well-small.clearfix
        .pull-left.qr-operates-upload
          .btn-group
            %a.btn.btn-picture-upload-single{:href => current_qr_upload_shops_path(:format => :js),
            "data-origin-href" =>  current_qr_upload_shops_path(:format => :js),
            "data-method" => :put,
            "data-disable-with" => "正在上传...",
            "data-remote" => true,:rel => "nofollow",
            "data-toggle" => "tooltip",:title => "将二维码放入淘宝图片空间"}
              %i.icon-cloud-upload
              上传到淘宝图片空间

            %a.btn.btn-download-qr-single{:href => current_download_qr_shops_path,
            "data-origin-href" =>   current_download_qr_shops_path,
            "data-no-turbolink" => true,
            "data-toggle" => "tooltip",:title => "下载二维码图片到本地"}
              %i.icon-download-alt
              下载到本地

        .pull-right.qr-operates-share
          <!-- Baidu Button BEGIN -->
          #bdshare.bdshare_t.bds_tools.get-codes-bdshare.shop-url-share{:data => "#{shop_share_json(@shop)}"}
            %a.bds_qzone  QQ空间
            %a.bds_tsina 新浪微博
            %a.bds_tqq 腾讯微博
            %a.bds_renren 人人网
            %span.bds_more 更多
          = render "shared/bdshare"
          <!-- Baidu Button END -->
      .well.well-small.qr-url
        .input-prepend.input-append{"data-toggle" => "tooltip","data-placement" => "bottom",:title => "拷贝图片网址到剪贴板"}
          %span.add-on
            %i.icon-link
          %span#qr_code_img_url.span8.uneditable-input{"data-origin-url" => public_qr_code_service_shops_url(content: shop_url(@shop.sid))} 
            = public_qr_code_service_shops_url(content: shop_url(@shop.sid))
          %a#btn_clip.btn.btn-clip{"data-clipboard-target" => 'qr_code_img_url',:type => :button}
            %i.icon-copy

        .alert.alert-success.clip-success{style: 'display : none;'}
          已将二维码网址复制到剪贴版

        .alert.alert-info
          您可复制该URL到需要显示的地方


%h4 评论
.row
  .span12
    .well
      -#Duoshuo Comment BEGIN
      .ds-thread{"data-title" => "店铺网址二维码","data-author-key" => taobao_nick,"data-url" => current_shops_url}
      -#Duoshuo Comment END