config/routes.rb
TaobaoQrcode::Application.routes.draw do

  resources :feedbacks

  resources :logos

  root 'shops#current'

  concern :public_qr_code_service do
    collection do
      get :public_qr_code_service
    end
  end
  resources :items,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :download_zip
    end
    member do
      get :download_qr
      put :img_upload
      put :picture_upload
      get :qr_code_img
    end
  end

  resources :shops,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :current
      get :current_download_qr
      get :current_qr_code_img
      put :current_qr_upload

      get :current_card
      put :generate_card

      get :current_card_download_qr
      get :current_card_qr_code_img
      put :current_card_qr_upload
    end
  end
  get 'dashboard/faq' => 'dashboard#faq',as: :faq
  get 'dashboard/history' => 'dashboard#index',as: :history
  get '/:id' => "shortener/shortened_urls#show"
  post 'short_url/generate' => "short_url#generate"

  

end

app/models/logo.rb
#coding: utf-8
class Logo < ActiveRecord::Base
  has_attached_file :img, :styles => { :medium => "300x300>", :thumb => "50x50" }, :default_url => "/images/:style/missing.png"
  validates_presence_of :nick,:img
end

app/controllers/logos_controller.rb
#coding: utf-8
#logo 上传记录
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]

  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.where(nick: session[:taobao_access_token]['taobao_user_nick'])
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)
    @logo.nick = taobao_nick
    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @logo }
      else
        format.html { render action: 'new' }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit!
    end
end

app/helpers/logos_helper.rb
module LogosHelper
  #获取paperclip的绝对url
  def absolute_logo_url(logo,attachment_style = :original)
    "#{request.protocol}#{request.host_with_port}#{logo.img.url(attachment_style)}"
  end
end

app/views/logos/_form.html.haml
= form_for @logo do |f|
  - if @logo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@logo.errors.count, "error")} prohibited this logo from being saved:"
      %ul
        - @logo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nick
    = f.text_field :nick
  .actions
    = f.submit 'Save'

app/views/logos/edit.html.haml
%h1 Editing logo

= render 'form'

= link_to 'Show', @logo
\|
= link_to 'Back', logos_path

app/views/logos/index.html.haml
%h1 Listing logos

%table
  %tr
    %th Nick
    %th
    %th
    %th

  - @logos.each do |logo|
    %tr
      %td= logo.nick
      %td= link_to 'Show', logo
      %td= link_to 'Edit', edit_logo_path(logo)
      %td= link_to 'Destroy', logo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Logo', new_logo_path

app/views/logos/new.html.haml
%h1 New logo

= render 'form'

= link_to 'Back', logos_path

app/views/logos/show.html.haml
%p#notice= notice

%p
  %b Nick:
  = @logo.nick

= link_to 'Edit', edit_logo_path(@logo)
\|
= link_to 'Back', logos_path