config/routes.rb
TaobaoQrcode::Application.routes.draw do

  resources :feedbacks

  resources :logos

  root 'shops#current'

  concern :public_qr_code_service do
    collection do
      get :public_qr_code_service
    end
  end
  resources :items,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :download_zip
    end
    member do
      get :download_qr
      put :img_upload
      put :picture_upload
      get :qr_code_img
    end
  end

  resources :shops,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :current
      get :current_download_qr
      get :current_qr_code_img
      put :current_qr_upload

      get :current_card
      put :generate_card

      get :current_card_download_qr
      get :current_card_qr_code_img
      put :current_card_qr_upload
    end
  end
  get 'dashboard/faq' => 'dashboard#faq',as: :faq
  get 'dashboard/history' => 'dashboard#index',as: :history
  get '/:id' => "shortener/shortened_urls#show"
  post 'short_url/generate' => "short_url#generate"

  

end

app/models/feedback.rb
#coding: utf-8
#用户反馈
class Feedback < ActiveRecord::Base
  validates_presence_of :nick,:feedback_message
end

app/controllers/feedbacks_controller.rb
#coding: utf-8
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    flash[:success] = "非常感谢您的反馈,我们会继续努力!"
    @feedback = Feedback.new(feedback_params)
    @feedback.save
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params[:feedback] ||= {
        feedback_name: params[:name],
        feedback_message: params[:message],
        nick: taobao_nick
      }
      params.require(:feedback).permit(:nick, :feedback_name, :feedback_message)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.haml
= form_for @feedback do |f|
  - if @feedback.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feedback.errors.count, "error")} prohibited this feedback from being saved:"
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nick
    = f.text_field :nick
  .field
    = f.label :feedback_name
    = f.text_field :feedback_name
  .field
    = f.label :feedback_message
    = f.text_area :feedback_message
  .actions
    = f.submit 'Save'

app/views/feedbacks/create.js.erb
$.notifyBar({
    cssClass: 'alert alert-success',
    html: "非常感谢您的反馈,我们会继续努力!",
    delay: 5000,
    animationSpeed: "normal",
  }); 
  $('.jquery-notify-bar').addClass('alert').addClass('alert-success')

app/views/feedbacks/edit.html.haml
%h1 Editing feedback

= render 'form'

= link_to 'Show', @feedback
\|
= link_to 'Back', feedbacks_path

app/views/feedbacks/index.html.haml
%h1 Listing feedbacks

%table
  %tr
    %th Nick
    %th Feedback name
    %th Feedback message
    %th
    %th
    %th

  - @feedbacks.each do |feedback|
    %tr
      %td= feedback.nick
      %td= feedback.feedback_name
      %td= feedback.feedback_message
      %td= link_to 'Show', feedback
      %td= link_to 'Edit', edit_feedback_path(feedback)
      %td= link_to 'Destroy', feedback, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feedback', new_feedback_path

app/views/feedbacks/new.html.haml
%h1 New feedback

= render 'form'

= link_to 'Back', feedbacks_path

app/views/feedbacks/show.html.haml
%p#notice= notice

%p
  %b Nick:
  = @feedback.nick
%p
  %b Feedback name:
  = @feedback.feedback_name
%p
  %b Feedback message:
  = @feedback.feedback_message

= link_to 'Edit', edit_feedback_path(@feedback)
\|
= link_to 'Back', feedbacks_path