config/routes.rb
TaobaoQrcode::Application.routes.draw do

  resources :feedbacks

  resources :logos

  root 'shops#current'

  concern :public_qr_code_service do
    collection do
      get :public_qr_code_service
    end
  end
  resources :items,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :download_zip
    end
    member do
      get :download_qr
      put :img_upload
      put :picture_upload
      get :qr_code_img
    end
  end

  resources :shops,concerns: :public_qr_code_service,:only => [:index,:show] do
    collection do
      get :current
      get :current_download_qr
      get :current_qr_code_img
      put :current_qr_upload

      get :current_card
      put :generate_card

      get :current_card_download_qr
      get :current_card_qr_code_img
      put :current_card_qr_upload
    end
  end
  get 'dashboard/faq' => 'dashboard#faq',as: :faq
  get 'dashboard/history' => 'dashboard#index',as: :history
  get '/:id' => "shortener/shortened_urls#show"
  post 'short_url/generate' => "short_url#generate"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="baidu-site-verification" content="58a3797b4045e9d64f4d2ad3bd4103ca"/>
    <title><%= content_for?(:title) ? yield(:title) : "码掌柜:码到成功" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag "/favicon.ico" %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag 'html5shiv-printshiv' %>
      <%= respond_include_tags %>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-application-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">
            <span class='brand-text'>码掌柜</span>
          </a>
          <div class='login-info'>
            <i class="icon-user"></i>
            <%= session[:taobao_access_token]['taobao_user_nick'] %>
          </div> 

          <div class="container nav-collapse">
            <ul class="nav">
              <li class="<%= set_nav_active("shops") %>" >
                <%= link_to "店铺", current_shops_path  %>
              </li>
              <li class="<%= set_nav_active("items") %>" >
                <%= link_to "商品", items_path  %>
              </li>
              <li class="<%= set_nav_active("dashboard") %>">
                <%= link_to "上传历史", history_path  %>
              </li>
              <li>
                <%= link_to "FAQ", faq_path  %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container <%= first_visit? ? "#{params[:controller]}-#{params[:action]}-first-visit" : ""  %>">
        <%= bootstrap_flash %>
        <%= yield %>
      <hr/>
      <footer>
        <%= render "shared/duoshuo"%>
        <%= render "shared/footer" %>
        <%= render "shared/google_analytics" %>
      </footer>
    </div> <!-- /container -->
    <%= javascript_include_tag "application" %>
    </body>
</html>